apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: n8n
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.io
spec:
  project: default
  source:
    repoURL: https://8gears.container-registry.com/chartrepo/library
    chart: n8n
    targetRevision: "0.x"
    helm:
      values: |
        config:
          database:
            type: postgresdb
        persistence:
          enabled: true
          storageClass: rook-ceph-block
          size: 5Gi
  destination:
    server: https://kubernetes.default.svc
    namespace: automation
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
