---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak-db-secret
  namespace: auth
spec:
  encryptedData:
    password: AgClMIUF86jmU7VpPTjcsGezf+k0x+vucyGhhRcV8vau0jj1BRXmW8k44yLVWqkQVhxRq9W9OXIlRE9foYNZjVxsXXPLGp7nS7Rvm6gEBGB1aHPcbknDfGv3G81PF0QxhRYo9iKOkFhkZT67b7scOOxeQ2G8eCqr81FFFKlhKXCaFgOu44V0EwFLU2WbAZhJrToA+dr7tBzcY//zyeS4rCBGxwbjZVhbs+HDw6L9tavOnpyaIK3zjBye1318NL3dgLVLZWp7qD1WNCcXg/LsbUtw0LmXc2Pa9XFy5BZzOA2hI7sUIqYe2HMVOp1T++sGALUtrmQHbBTJKgalf0FmlE6VYTo5vlDr7wA5ytbWQC4zopG2a2VKcQhQjEF6ragbD9k6pFndSwtpX/DTHQWUq/4ytVFYYoL4rCIhqOXUJTBkQgUufdz6+RkG91NeZORjzPpR/r8lLK5AdGnRurh+RnyyLyLhx05yaUq6pF1XvksgecAZ4/xAlLjxxMIpxJd5pzYQdKZNXbZz05xkJTb/wo/nB4uvPjKgdvCbo0g5xgs/uEGjhnYRXKg6E6/1Yd84hUbsqmSUsA3rqyYv+qbpSi6Vn5l0aZcN1tYmk/s+slxpu+Smvl4S6HIR48yN4HH26DhfyDDewU7BoQ/RER7Qb+iZyLIxdXZyPBtbr4iFkChMLhBWEyQdHQsz7JcEihT6QCjXoNMm59BBxIjLPRpR14k=
    postgres-password: AgBM90P/7UkT0Z1PkpVUjtP1R33CBgRCFhwkrVT77MwxtxXj7gkqmIKQbPPP1AFXkGYCLi1gnu0pHVXot+rQxMQTK+7mFYffsr/58MBawNa8GVwuvMxSwbAOmOMcW0t4yUZQVpxFPkS6ULl569X6m6qypWDX6ym0iYZsEg1xBbh6fR7zzeJGnqvDMQXnEDF7CPoYs/CwKIMYh+MhidATHcYhxckmPmTnAvJAz5kyZAoNens6Zm1V58UwzTsrVLSfaNl8PAwMyblWIgDWmNGVgXpfajW7X8Qi1pGZWmG2I5yar0tll+KtKB8G8dObdaVInGdYWEr9kjRZbytbekPCslqKx6x6N3Lj6P/bVkgIV7AIoHZtn2S/LMSlaHYAA1Oqwchuf1CF3pRjFz9q5nBFqCWoPGWdOCeNlS0o8Z20DrOnVyLaFNi+vU3U4j0G8mJfYPiZAwmbhqcqWTVDvQvjG8zhYa0r2swlxZz0QLF/R88XM5Zm9KC6/O6ERfjaiw17yZUGGcYUiz6g26KIVL0ugezZ0DjHYLf72F8hYOgXnkAwFQsTCnlq7Bk/5ggEwuIqtr95eX5NNdxXHoLvHEU1i7dT4Lk61EcK10iojt/hA+iRahQyI/kSuX3yEkyFLZvmIhaGFMlGV/gs4jcbsIqNuR4aLNNN5+1UKfrJG/MyTn4hYdBzrREBMrebVyn15jFPgGPAj1BdTbBGFQ3C10M=
  template:
    metadata:
      creationTimestamp: null
      name: keycloak-db-secret
      namespace: auth
