---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak-admin-secret
  namespace: auth
spec:
  encryptedData:
    admin-password: AgBBEs53c30di4lCqfVpmml9qxxESm0cbHIaHauvEdTQFs4E3fxD8Z4hOuBUj1fMi/MUChEpkYqmcLcawm9cSlanO18WZdvEVyFWuqwKKJBQcUD0w5eSzoUvl8oYcA540n3xniMyecrDDquTKzm+Jp8LiPiO6SuYCu6W1/HB/RR2Ril+8wB9aPrrs5+T4xBZwr27UrXIAoPEZ91fs1Iqo0WhDgOB1roXWogosxnNbI+KPSQyF6r4ib/xdz+Zgo0K6ldCSIgxSbAi3YHBqD34Q7zUKse8SSQK0SCRFDCSE3rDdL9/B+VymkcZ57sCDiNDsAzjbYHrBwCrSIFGLvNPnONWi7R7JXYmySmeregLwS2xFVZNz97BINdy4JxBOBTYiVz/Uo1MMsMNnP/44rp0ti7plXMIn+gaU7enIqqjFomwbY8zF9Mb/h0AGldd+Dk6imdAkx+fRSB1zHgUJNqzDsiq17+wGd64pw1NhOVXmExfKzRbNNZ1E1dARaYL/osVUqNqyfWJTbNYLSJbgCACIfm6QJmWntM1PrpADPS9bjXQrkadwFl8JHEYnzlnBJIBIJTTquomUz3IbX6dO/JV4Em/wcQirSc2wg8Qzo2TO3J6dMkrofzD4xpPVfjAycw8iJjrR7ww61yLNM0+7YH9GRJl1cepZ/sl9T7XOEN6w/FzGfmRV13mH7LE6EZC7s9CJbPnws7fRExQhgA/5WUV
  template:
    metadata:
      creationTimestamp: null
      name: keycloak-admin-secret
      namespace: auth
