---
- name: Installer dépendances apt
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
    state: present
  tags: kubernetes

- name: Créer dossier keyrings
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'
  tags: kubernetes

- name: Télécharger clé GPG Kubernetes
  shell: |
    curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.28/deb/Release.key \
    | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
  args:
    creates: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
  tags: kubernetes

- name: Ajouter repo Kubernetes
  copy:
    dest: /etc/apt/sources.list.d/kubernetes.list
    content: |
      deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.28/deb/ /
  tags: kubernetes

- name: Installer kubelet kubeadm kubectl
  apt:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: present
    update_cache: yes
  tags: kubernetes

- name: Bloquer les mises à jour automatiques
  dpkg_selections:
    name: "{{ item }}"
    selection: hold
  loop:
    - kubelet
    - kubeadm
    - kubectl
  tags: kubernetes
