name: Ansible

on:
  push:
    branches: [main]
    paths:
      - 'ansible/**'
  workflow_run:
    workflows: ["Terraform"]
    types:
      - completed
    branches: [main]

jobs:
  ansible:
    name: Ansible Bootstrap K8s
    runs-on: self-hosted
    if: >
      github.event_name == 'push' ||
      github.event.workflow_run.conclusion == 'success'
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Download Terraform outputs
        uses: actions/download-artifact@v4
        with:
          name: terraform-outputs
          path: infra/
        continue-on-error: true

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.K8S_MASTER_IP }} >> ~/.ssh/known_hosts
          ssh-keyscan -H ${{ secrets.K8S_WORKER1_IP }} >> ~/.ssh/known_hosts
          ssh-keyscan -H ${{ secrets.K8S_WORKER2_IP }} >> ~/.ssh/known_hosts

      - name: Install Ansible
        run: |
          if ! command -v ansible &> /dev/null; then
            pip install ansible --quiet --break-system-packages
          fi

      - name: Run Ansible Playbook
        working-directory: ansible/
        run: ansible-playbook -i inventory.ini site.yml