name: K8s Lab CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  terraform:
    name: Terraform Validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3.1.2
        with:
          terraform_version: 1.9.8

      - name: Terraform Init
        working-directory: ./infra
        run: terraform init -backend=false -input=false

      - name: Terraform Validate
        working-directory: ./infra
        env:
          TF_VAR_proxmox_api_url: "https://fake:8006"
          TF_VAR_proxmox_token_id: "fake@pam!token"
          TF_VAR_proxmox_token_secret: "fake-secret"
          TF_VAR_ssh_public_key: "ssh-ed25519 AAAAC fake key"
        run: terraform validate

      - name: Checkov
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: infra/
          soft_fail: true

  ansible:
    name: Ansible Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2

      - name: Install Ansible + lint
        run: |
          sudo apt-get update -q
          sudo apt-get install -y ansible python3-pip
          pip3 install ansible-lint

      - name: Run ansible-lint
        run: ansible-lint ansible/ --warn-list=all || true